### ISSUE TITLE
我阅读了您的文章，觉得非常不错，而且它可能适用于我的问题。我真诚地希望您能贡献数据集、推理代码以及训练权重，为社区做出贡献。

### ISSUE THREAD

**Issue by PhamLongVu** [GuohaoCui/DiffusionModel#1]

**Comment by GuohaoCui** [comment]
Hello, thank you very much for your affirmation of our work. At present, we have uploaded the dataset and weights to Google Drive. The link can be viewed in the README.

**Comment by PhamLongVu** [comment]
Please grant access to the dataset and weights in the drive, thanks for public in comunication.

**Comment by GuohaoCui** [comment]
We had incorrect settings before. Now we have made the dataset and weights publicly available.

**Comment by PhamLongVu** [comment]
@GuohaoCui let me ask how much GPU capacity is needed to train the model
